In [1]:
import sqlite3
import pandas as pd

In [2]:
con = sqlite3.connect('../data/raw/imessage/chat.db')

In [3]:
sql = "SELECT name FROM sqlite_master WHERE type='table'"
tables = pd.read_sql(sql, con)

In [4]:
tables

                         name
0   _SqliteDatabaseProperties
1                     message
2             sqlite_sequence
3                        chat
4                  attachment
5                      handle
6     message_attachment_join
7            chat_handle_join
8           chat_message_join
9            deleted_messages
10      sync_deleted_messages
11    message_processing_task
12         sync_deleted_chats
13   sync_deleted_attachments
14                    kvtable
15               sqlite_stat1

In [5]:
sql = "SELECT * FROM message"
messages = pd.read_sql(sql, con)
messages.tail()

,ROWID,guid,text,replace,service_center,handle_id,subject,country,attributedBody,version,...,ck_record_id,ck_record_change_tag,destination_caller_id,sr_ck_sync_state,sr_ck_record_id,sr_ck_record_change_tag,is_corrupt,reply_to_guid,sort_id,is_spam
31061,31099,E4A59581-BFEE-43B3-B436-55C37C07465A,Such a faff,0,None,62,None,None,b'\x04\x0bstreamtyped\x81\xe8\x03\x84\x01@\x84...,10,...,,,+447792409067,0,,,0,F6F5FCB3-EC33-40FF-A410-4055A87B5F1F,0,0
31062,31100,70984ABC-F655-4D68-A4DC-496C7E8833F2,And I’m quite jealous of all the people who’ll...,0,None,62,None,None,b'\x04\x0bstreamtyped\x81\xe8\x03\x84\x01@\x84...,10,...,,,+447792409067,0,,,0,E4A59581-BFEE-43B3-B436-55C37C07465A,0,0
31063,31101,C8C4EFCA-D019-4E59-882C-F6A37F4B06A2,Loo roll shortages will only get worse,0,None,62,None,None,b'\x04\x0bstreamtyped\x81\xe8\x03\x84\x01@\x84...,10,...,,,+447792409067,0,,,0,70984ABC-F655-4D68-A4DC-496C7E8833F2,0,0
31064,31102,F71C80A5-ECAE-46C9-A39B-5688C0501A14,Then you’ll really need to be careful about wa...,0,None,62,None,None,b'\x04\x0bstreamtyped\x81\xe8\x03\x84\x01@\x84...,10,...,,,+447792409067,0,,,0,C8C4EFCA-D019-4E59-882C-F6A37F4B06A2,0,0
31065,31103,9D23696F-7BF5-471E-862C-83DB88118180,Laughed at “Then you’ll really need to be care...,0,None,62,None,None,b'\x04\x0bstreamtyped\x81\xe8\x03\x84\x01@\x84...,10,...,None,None,+447792409067,0,None,None,0,F71C80A5-ECAE-46C9-A39B-5688C0501A14,0,0

In [130]:
sql = "SELECT * from chat"
chat = pd.read_sql(sql, con)
chat.tail()

,ROWID,guid,style,state,account_id,properties,chat_identifier,service_name,room_name,account_login,...,ck_sync_state,last_read_message_timestamp,ck_record_system_property_blob,original_group_id,sr_server_change_token,sr_ck_sync_state,cloudkit_record_id,sr_cloudkit_record_id,last_addressed_sim_id,is_blackholed
103,105,iMessage;-;+447717844213,45,3,3A624DF0-08E5-4D45-8EFD-05EFC3C840D9,b'bplist00\xd6\x01\x02\x03\x04\x05\x06\x07\x08...,+447717844213,iMessage,None,E:edward.r.rees@zoho.com,...,0,594567908692263936,None,A8BF353A-18A3-4277-B333-91D95C2E33D8,,0,,,None,0
104,106,SMS;-;+447717844213,45,3,C5592D54-9D20-4106-AEA6-EFE5D6228C55,b'bplist00\xd1\x01\x02_\x10#CKChatPreviousAcco...,+447717844213,SMS,None,E:,...,0,0,None,56A3B88DCA1262711F8205BAD8D253584E4078DA,,0,,,None,0
105,107,iMessage;-;+447751870091,45,3,3A624DF0-08E5-4D45-8EFD-05EFC3C840D9,b'bplist00\xd4\x01\x02\x03\x04\x05\x06\t\nRpv_...,+447751870091,iMessage,None,E:edward.r.rees@zoho.com,...,0,605890938003845632,None,BB22956F-73C9-40ED-B4AA-CC93F4B2972F,,0,,,None,0
106,108,iMessage;-;+447792955159,45,3,3A624DF0-08E5-4D45-8EFD-05EFC3C840D9,b'bplist00\xd3\x01\x02\x03\x04\x07\x08_\x10%co...,+447792955159,iMessage,None,E:edward.r.rees@zoho.com,...,0,602273171228137728,None,D22686AB-9CBD-423C-8B9A-3BC7FDC8B5E5,,0,,,None,0
107,109,iMessage;-;+447522912340,45,3,3A624DF0-08E5-4D45-8EFD-05EFC3C840D9,b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\nRp...,+447522912340,iMessage,None,E:edward.r.rees@zoho.com,...,0,605873639485800704,None,91824DD6-E037-48AF-9A9A-2E9D27ACA486,,0,,,None,0